# Site Settings
title: Marc Enschede
email: marc@marcenschede.nl
description: Software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.marcenschede.nl" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Marc Enschede
user_description: Software developer.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: enschede
#facebook_username: facebook_username
twitter_username: marcenschede
#instagram_username: instagram_username
linkedin_username: marcenschede
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
